version: '3.8'

services: 
    redis:
        image: redis:6.2.4-alpine
        container_name: gon-redis
        restart: always
        ports:
            - 6379:6379

    postgres:
        image: postgres:alpine
        container_name: gon-postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: yahia
            POSTGRES_PASSWORD: 2472BvZFgUNrof

    go-nsistency:
        image: gon
        container_name: gon
        depends_on: 
            - redis
            - postgres
        restart: always
        environment:
            GON_PORT: 8000
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8000:8000

    pgadmin:
        container_name: gon-pgadmin
        restart: always
        image: dpage/pgadmin4:5.4
        environment:
            - PGADMIN_DEFAULT_EMAIL=ymr_15@live.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - 5431:80
